# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170405_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 5, 16, 27, 44, 453841, tzinfo=utc)),
        ),
    ]
