# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 16:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170406_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 9, 16, 43, 51, 387608, tzinfo=utc)),
        ),
    ]
